name: remix
description: Completely unstyled, widgets designed to integrate with Mix
repository: https://github.com/btwld/mix/tree/main/packages/remix
homepage: https://www.fluttermix.com/
publish_to: none

version: 0.0.4+2

environment:
  sdk: ">=3.6.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  mix: ^1.7.0-beta.0
  mix_annotations: ^1.7.0-beta.0
  naked:
    path: ../naked
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mix_generator: ^1.7.0-beta.0
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  dart_code_metrics_presets: ^2.14.0
  

flutter:
  uses-material-design: true
